# Generated by Marten 0.3.2 on 2023-09-12 09:03:50 -04:00

class Migration::Main::V202309120903501 < Marten::Migration
  depends_on :main, "202309010118281_auto"

  def plan
    create_table :main_service do
      column :id, :big_int, primary_key: true, auto: true
      column :name, :string, max_size: 40
    end

    create_table :main_agent do
      column :id, :uuid, primary_key: true, unique: true
      column :name, :string, max_size: 40
      column :version, :string, max_size: 25
    end

    remove_column :main_alert, :host_id

    delete_table :main_host

    add_column :main_service, :agent_id, :reference, to_table: :main_agent, to_column: :id

    add_column :main_alert, :agent_id, :reference, to_table: :main_agent, to_column: :id
  end
end
