# Generated by Marten 0.3.2 on 2023-11-26 23:50:58 -05:00

class Migration::Main::V202311262350581 < Marten::Migration
  depends_on :main, "202311262348401_auto"

  def plan
    change_column :main_agent, :created_at, :date_time

    change_column :main_agent, :updated_at, :date_time
  end
end
