# Generated by Marten 0.3.2 on 2023-09-01 01:18:28 -04:00

class Migration::Main::V202309010118281 < Marten::Migration
  depends_on :main, "202308312357341_create_main_host_table"

  def plan
    create_table :main_alert do
      column :id, :big_int, primary_key: true, auto: true
      column :host_id, :reference, to_table: :main_host, to_column: :id
    end
  end
end
